"""Compose a SKILL.md artifact from a SkillSpec.

Output structure:
1. YAML frontmatter (name, description, allowed-tools)
2. DO-NOT-EDIT generation marker
3. Baseline body (from package resources)
4. Catalog section (dynamic, from catalog_fn if present)
"""

from __future__ import annotations

from metaproc.skill.spec import SkillSpec


def compose_skill(spec: SkillSpec) -> str:
    """Compose the full SKILL.md content for the given spec.

    The output is deterministic for a given spec state — no timestamps or
    random components.
    """
    parts: list[str] = []

    # 1. YAML frontmatter
    parts.append("---")
    parts.append(f"name: {spec.name}")
    # Use YAML block scalar for multi-line or long descriptions
    if "\n" in spec.description or len(spec.description) > 70:
        parts.append("description: >-")
        for line in spec.description.splitlines():
            parts.append(f"  {line}")
    else:
        parts.append("description: >-")
        parts.append(f"  {spec.description}")
    if spec.allowed_tools:
        parts.append(f"allowed-tools: {spec.allowed_tools}")
    parts.append("---")

    # 2. DO-NOT-EDIT marker
    parts.append(
        f"<!-- GENERATED by `metaproc skill {spec.name} --install`. "
        "DO NOT EDIT; regenerate with `metaproc skill "
        f"{spec.name} --install` -->"
    )
    parts.append("")

    # 3. Baseline body
    baseline = spec.load_baseline()
    parts.append(baseline.rstrip())

    # 4. Catalog section (if present)
    if spec.catalog_fn is not None:
        catalog = spec.catalog_fn()
        if catalog.strip():
            parts.append("")
            parts.append(catalog.rstrip())

    # Final newline
    parts.append("")
    return "\n".join(parts)
