"""Reference model for the execution model: the kernel of durable execution contracts.

This package is the executable form of ``docs/execution-model-design.md``: the durable
facts a run is made of, and a pure reducer over them. It deliberately performs no I/O
and reads no clock, so scheduler semantics can be tested without processes, files, or
timing. The production engine is checked against it; it does not replace the engine.
"""

from metaproc.kernel.model import (
    DEFAULT_RETRY_POLICY,
    AttemptDisposition,
    AttemptRecord,
    Cardinality,
    ClauseMapping,
    CommitRecord,
    DependencyClause,
    ExpansionRecord,
    ExpansionState,
    KernelState,
    Outcome,
    Requirement,
    RetryPolicy,
    StepTemplate,
    TaskKey,
    TaskRecord,
    TaskState,
)
from metaproc.kernel.projection import (
    PROJECTION_CONTRACT,
    Blocker,
    BlockerKind,
    ProcessStatus,
    StepView,
    TaskView,
    blocker_for,
    project,
)
from metaproc.kernel.reducer import (
    AttemptEnded,
    AttemptStarted,
    CancelAttempt,
    CommandType,
    DispatchAttempt,
    Event,
    ExpansionClosed,
    ExpansionFailed,
    ForceIssued,
    MaterializeExpansion,
    ScheduleRetry,
    Tick,
    reduce,
    retry_policy_for,
)

__all__ = [
    "DEFAULT_RETRY_POLICY",
    "PROJECTION_CONTRACT",
    "AttemptDisposition",
    "AttemptEnded",
    "AttemptRecord",
    "AttemptStarted",
    "CancelAttempt",
    "Cardinality",
    "ClauseMapping",
    "CommandType",
    "CommitRecord",
    "DependencyClause",
    "DispatchAttempt",
    "Event",
    "ExpansionClosed",
    "ExpansionFailed",
    "ExpansionRecord",
    "ExpansionState",
    "ForceIssued",
    "KernelState",
    "MaterializeExpansion",
    "Outcome",
    "Requirement",
    "RetryPolicy",
    "ScheduleRetry",
    "StepTemplate",
    "TaskKey",
    "TaskRecord",
    "TaskState",
    "Tick",
    "Blocker",
    "BlockerKind",
    "ProcessStatus",
    "StepView",
    "TaskView",
    "blocker_for",
    "project",
    "reduce",
    "retry_policy_for",
]
